import type { GateResult, Comparison, CaseComparison } from "../stats/compare.js";
import { formatCost, formatMs } from "./console.js";
import { countsLine, fmtDate, pct, pctWithInterval, points, runLine } from "./format.js";
import type { RunReport } from "./model.js";

/** Make text safe for a single Markdown table cell. */
export function cell(text: string, max = 140): string {
  const one = text.replace(/\s+/g, " ").trim().replace(/\|/g, "\\|").replace(/</g, "&lt;");
  return one.length > max ? `${one.slice(0, max - 1)}…` : one;
}

const VERDICT_ICON = { passed: "✓", failed: "✗", flaky: "~", errored: "!" } as const;
const CHANGE_ICON: Record<CaseComparison["change"], string> = {
  regressed: "✗",
  improved: "✓",
  unchanged: "·",
  flaky: "~",
  modified: "·",
  new: "·",
  removed: "·",
  errored: "!",
};

function reasonFor(c: RunReport["cases"][number]): string {
  for (const a of c.attempts) {
    if (a.error) return `error: ${a.error}`;
    const bad = a.scores.find((s) => s.error || !s.pass);
    if (bad) return `${bad.scorerName}: ${bad.error ? `error: ${bad.error}` : (bad.reasoning ?? "failed")}`;
  }
  return "";
}

/** A run summary suitable for a GitHub job summary or PR comment. */
export function renderRunMarkdown(report: RunReport, version = ""): string {
  const s = report.summary;
  const r = report.run;
  const ok = s.cases.passed === s.cases.total;
  const lines: string[] = [];
  lines.push(`## Regrade · ${r.suiteName}`);
  lines.push("");
  lines.push(
    ok
      ? `**✓ All ${s.cases.total} case${s.cases.total === 1 ? "" : "s"} passed**`
      : `**✗ ${s.cases.total - s.cases.passed} of ${s.cases.total} cases did not pass**`,
  );
  lines.push("");
  lines.push(
    `passed ${s.cases.passed} · failed ${s.cases.failed} · flaky ${s.cases.flaky} · errored ${s.cases.errored}` +
      (s.attempts.total !== s.cases.total ? ` · ${s.attempts.total} attempts` : ""),
  );
  lines.push("");
  const meta = [`run \`${r.runId.slice(0, 8)}\``, fmtDate(r.startedAt)];
  if (r.label) meta.push(r.label);
  if (r.gitSha) meta.push(`\`${r.gitSha.slice(0, 7)}${r.gitDirty ? "*" : ""}\``);
  if (r.status !== "completed") meta.push(`_${r.status}_`);
  lines.push(meta.join(" · "));
  if (s.latency) lines.push(`latency avg ${formatMs(s.latency.avgMs)} · p95 ${formatMs(s.latency.p95Ms)} · cost ${formatCost(s)}`);
  lines.push("");

  const attention = report.cases.filter((c) => c.verdict !== "passed");
  if (attention.length > 0) {
    lines.push("| | Case | Attempts passed | Why |");
    lines.push("|---|---|---|---|");
    for (const c of attention) {
      const passed = c.attempts.filter((a) => a.status === "passed").length;
      lines.push(`| ${VERDICT_ICON[c.verdict]} ${c.verdict} | \`${cell(c.caseId, 60)}\` | ${passed}/${c.attempts.length} | ${cell(reasonFor(c))} |`);
    }
    lines.push("");
  }
  const passing = report.cases.filter((c) => c.verdict === "passed");
  if (passing.length > 0) {
    lines.push(`<details><summary>${passing.length} passing case${passing.length === 1 ? "" : "s"}</summary>`);
    lines.push("");
    lines.push(passing.map((c) => `\`${cell(c.caseId, 60)}\``).join(" · "));
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }
  lines.push(`<sub>Generated by Regrade${version ? ` ${version}` : ""}</sub>`);
  return `${lines.join("\n")}\n`;
}

/** A comparison suitable for a GitHub job summary or PR comment. */
export function renderCompareMarkdown(cmp: Comparison, gate?: GateResult, version = ""): string {
  const o = cmp.overall;
  const lines: string[] = [];
  lines.push(`## Regrade compare · ${cmp.head.suiteName}`);
  lines.push("");
  if (gate) {
    lines.push(gate.failed ? `**✗ Regression gate failed:** ${cell(gate.reasons.join("; "), 400)}` : "**✓ No regressions**");
  } else {
    const n = cmp.counts.regressed;
    lines.push(n > 0 ? `**✗ ${n} regressed case${n === 1 ? "" : "s"}**` : "**✓ No regressed cases**");
  }
  lines.push("");
  lines.push(`- base: ${runLine(cmp.base)}`);
  lines.push(`- head: ${runLine(cmp.head)}`);
  lines.push(`- cases: ${countsLine(cmp.counts)}`);
  if (o.base && o.head) {
    lines.push(`- attempt pass rate: ${pctWithInterval(o.base)} → ${pctWithInterval(o.head)} _(${o.comparableCases} comparable cases; descriptive)_`);
  }
  if (o.meanDelta !== null) {
    const ci = o.ci ? `, 95% CI [${points(o.ci.lo)}, ${points(o.ci.hi)}]` : "";
    const p = o.pValue === null ? "" : `, p=${o.pValue < 0.0001 ? "<0.0001" : o.pValue.toFixed(4)}`;
    const verdict = o.verdict.replace(/-/g, " ");
    lines.push(`- overall change (case-stratified permutation test): mean per case ${points(o.meanDelta)}${ci}${p} → **${verdict}**`);
  }
  for (const w of cmp.warnings) lines.push(`- ⚠ ${cell(w, 300)}`);
  lines.push("");

  const changed = cmp.cases.filter((c) => c.change !== "unchanged");
  if (changed.length > 0) {
    lines.push("| | Case | Base | Head | Change | Note |");
    lines.push("|---|---|---|---|---|---|");
    for (const c of changed) {
      const b = c.base ? `${c.base.passed}/${c.base.attempts} (${pct(c.base.rate)})` : "–";
      const h = c.head ? `${c.head.passed}/${c.head.attempts} (${pct(c.head.rate)})` : "–";
      const p = c.pValue !== undefined && (c.change === "regressed" || c.change === "improved") ? ` p=${c.pValue.toFixed(3)}` : "";
      lines.push(`| ${CHANGE_ICON[c.change]} | \`${cell(c.caseId, 60)}\` | ${b} | ${h} | ${c.change}${p}${c.significant ? " (significant)" : ""} | ${cell(c.note ?? "", 110)} |`);
    }
    lines.push("");
  }
  if (cmp.counts.unchanged > 0) {
    lines.push(`<sub>${cmp.counts.unchanged} unchanged case${cmp.counts.unchanged === 1 ? "" : "s"} not listed.</sub>`);
  }
  lines.push("");
  lines.push(`<sub>Generated by Regrade${version ? ` ${version}` : ""}</sub>`);
  return `${lines.join("\n")}\n`;
}
